service: trade

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8

functions:
  rateHandler:
    handler: handler.run
    # memory
    memorySize: 256
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 minute)

plugins:
  - serverless-python-requirements
