service: trade

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8

functions:
  rateHandler:
    handler: handler.run
    memorySize: 256
    events:
      - schedule: rate(1 day)

plugins:
  - serverless-python-requirements
