service: trade

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  iam:
    role:
      statements:
        # Allow functions to read/write objects in a bucket
        - Effect: Allow
          Action:
            - "s3:GetObject"
            - "s3:PutObject"
          Resource: "arn:aws:s3:::trade-store"

functions:
  tradePerHour:
    handler: handler.run_per_1h
    memorySize: 512
    events:
      - schedule: rate(1 hour)
  tradePerMinute:
    handler: handler.run_per_1m
    memorySize: 512
    events:
      - schedule: rate(1 minute)

plugins:
  - serverless-python-requirements
